
-- 切换动画
-- if key == "1" then 
--     local iAnimateSys = self.tbCurScene:GetSystemByName("AnimationSystem");
--     self.iPlayer:ChangeiCompoParam({
--         ["Animate"] = { sImg = "ball", nQuadW = 32, nQuadH = 32, nTotalFrame= 5, nLoop = 1, nTotalPlayCount = 10,nTimeAfterPlay = 0.07 };
--     })
--     iAnimateSys:ReSetFrame(self.iPlayer);
--     iAnimateSys:Play(self.iPlayer);
-- end 
-- if key == "2" then 
--     local iAnimateSys = self.tbCurScene:GetSystemByName("AnimationSystem");
--     self.iPlayer:ChangeiCompoParam({
--         ["Animate"] = { sImg = "tc", nQuadW = 30, nQuadH = 55, nTotalFrame= 18, nLoop = 0, nTotalPlayCount = 5,nTimeAfterPlay = 0.07 };
--     })
--     iAnimateSys:ReSetFrame(self.iPlayer);
--     iAnimateSys:Play(self.iPlayer,function()
--         ActorMgr:RemoveActor(self.iPlayer)
--     end);
-- end